name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  docker:
    runs-on: ubuntu-latest
    needs:
    - test
    - clippy
    steps:
    - uses: actions/checkout@v2
    - name: Build Container Image
      run: DOCKER_BUILDKIT=1 docker build . -t ghcr.io/daniel0611/dhbw-dualis:latest

    - name: Log in to GHCR
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Container Image
      if: github.ref == 'refs/heads/main'
      run: docker push ghcr.io/daniel0611/dhbw-dualis:latest